### ISSUE TITLE
Request: offer to replace `TextUtils.isEmpty()` with Kotlin's `isNullOrEmpty()`

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [Miha-x64/Mikes_IDEA_extensions#10]
As the title says...
This can happen when converting from Java to Kotlin.

**Comment by AndroidDeveloperLB** [comment]
Why close? Was it added?

**Comment by Miha-x64** [comment]
As usual, there's a link to according commit above.

**Comment by AndroidDeveloperLB** [comment]
Thank you!

**Comment by AndroidDeveloperLB** [comment]
May I ask if this is a hard thing to work on?

**Comment by Miha-x64** [comment]
As usual, this depends on experience.
I think that this case is quite trivial:
- single language,
- only functions calls, no operators, no complicated constructs,
- the replacement requires minimal effort since the old and new methods accept identical parameters.

You can take a look at the commit yourself to get an idea about how it works.

**Comment by AndroidDeveloperLB** [comment]
I see. Thanks.
